[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "udlf-text-espresso"
version = "0.0.1"
description = "UDLF Text Espresso: experimental framework for text retrieval and reranking"
authors = [{ name = "Luis Venezian" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools]
packages = ["udlf_text_espresso"]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
udlf_text_espresso = ["**/*.yaml"]
